name: null
favicon: null
layout_spectrum: 0
typography_spectrum: 0.5
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0262b'
    - '#1e516d'
    - '#fed141'
    - '#844a8d'
    - '#c17003'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose: []
